DELIMITER//
CREATE PROCEDURE Sum TwoNumbers()
BEGIN
DECLARE num! INT DEFAULT 10;
DECLARE numz INT DEFAULT 20;
DECLARE total INT;
SET total = num! + num2;
SELECT total AS Sum;
ENP//
DELIMITER:
CALL Sum TwoNumbers();
